default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV["DB_POOL"] || 5  %>
  database: <%= ENV['DB_NAME'] || 'api_roj_development' %>
  username: <%= ENV['DB_USER'] || ENV['USER'] %>
  password: <%= ENV['DB_PASS'] %>
  host: <%= ENV["DB_HOST"] %>
  url: <%= ENV['DATABASE_URL'] %> # takes higher precedence than other settings
  reconnect: true

test:
  <<: *default
  database: api_roj_test

development:
  <<: *default
  database: <%= ENV['DB_NAME'] || 'api_roj_development' %>

staging:
  <<: *default
  database: api_roj_staging
  url: <%= ENV['STAGING_DATABASE_URL'] %>

production:
  <<: *default
  database: api_roj_production
  url: <%= ENV['PRODUCTION_DATABASE_URL'] %>
